Add debugDescription
JamitLabs/MungoHealer pull request #4
Opened 2018-10-23 12:52 UTC by insightmind

# Add debugDescription

This PR introduces the variable `debugDescription` as an addition to the BaseError protocol.
The `debugDescription` allows developers to have a distinct debug description and a localized description of the error.

Advantages of this implementation are, that developers can have a more concise and descriptive description of the error for debugging purposes while hiding all technical details from the user.

2018-10-24 21:00 UTC, Jeehut requested changes
This looks good overall, just two minor things, see comments below.

Could you please also update the README.md accordingly and add a changelog entry? Then I'll merge.

2018-10-24 21:00 UTC, Jeehut commented on Frameworks/MungoHealer/ErrorHandlers/AlertLogErrorHandler.swift
> +    private func log(_ error: Error) {
Why is this a "either this or that" but not a "if debug is given, add this, too". I mean, maybe somebody puts infos into the localized description and doesn't want to repeat that info, instead he just puts additonal details or plain data that belongs to the error to the debug description. I'd rather have the localized description logged, too even if the description exists. Maybe something like this:

```
logError("\(error.localizedDescription) | Details: \(debugDescription)")
```

2018-10-24 21:00 UTC, Jeehut commented on Frameworks/MungoHealer/ErrorHandlers/AlertLogErrorHandler.swift
> +        if let baseError = error as? BaseError, let description = baseError.debugDescription, !description.isBlank {
I'd prefer this local variable named `debugDescription` instead of `description`. It's clearer IMHO.

2018-10-29 10:51 UTC, insightmind commented on Frameworks/MungoHealer/ErrorHandlers/AlertLogErrorHandler.swift
> +    private func log(_ error: Error) {
Should be resolved.

2018-10-29 14:29 UTC, merged